# -*- coding: utf-8 -*-
"""u04_기본문법.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kE5YsJgWDw7Hw4r-iMfnBlOOZTUnEN_I

# Unit 4. 기본 문법 알아보기

## 4.1 세미콜론
"""

print("hello world!")

print('hello world!'); print('1234')

"""## 4.2 주석

### 4.2.1 한줄 주석
"""

# Hello, world! 출력
print('Hello, world!')

print('Hello, world!')      # 1 line comment type

"""### 4.2.2 블록주석"""

# 더하기
# a = 1 + 2
# print('Hello, world!')

# 더하기
''' a = 1 + 2
 print('Hello, world!') '''

"""이 안에 포함된 내용이 블록 주석

## 4.3 들여쓰기(Indentation)

C 프로그래밍 예
sum = 0;
for (i=1; i<=10; i++) {
  sum += i;
}
printf(sum);
"""

# 파이썬 예
sum = 0
for i in range(1,11):
  sum += i
  print(sum)  
print(sum)

# 기본 공백 : 스페이스 4개, 탭/백탭(shift+tab)
sum = 0
for i in range(1,11):
  sum += i
  if (i>9):
    print(i)
  
print(sum)

